version: '3'
services:
  app:
    env_file:
      - .development.env
    container_name: anthill_backend
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
    volumes:
      - /usr/src/app/node_modules
      - .:/usr/src/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - '5432:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
