version: '3'
services:
  app:
    env_file:
      - .development.env
    container_name: anthill_backend
    restart: always
    build: .
    ports:
      - '$PORT:$PORT'
    links:
      - postgres
    volumes:
      - /app/node_modules
      - .:/app
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev
    ports:
      - '5433:5432'
    volumes:
      - ./db-data:/var/lib/postgresql/data
